### PR TITLE
chore: add text for round in application state

### LINKED ISSUE #1761: Builder: update Application Landing page for when applications have not opened yet
**User Stories**
As a project owner 
I want to know if the application period for a round has started yet 
So that I know when I can start applying 

**Acceptance Criteria**
GIVEN that applications have not started
WHEN I look at the page 
THEN I see information about applications starting on X date
AND a disabled Apply CTA

**Product & Design links**
* [Figma](https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Builder-S17?type=design&node-id=4891-39873&t=AXp18ripODoi3NBL-4) 
* Try: https://staging.grantshub.gitcoin.co/#/chains/5/rounds/0xd8b77930ff589a27a7c15d825eb04860669da56b

### PR DESCRIPTION
**Pull request by thelostone-mc**
Refs #1761

### CODE REVIEW

**Review by KurtMerbeth — APPROVED** [review]

**Comment by michellema1208** [comment]
@thelostone-mc - it says the "gitcoin-buiilder-staging" build is queued, so I'm not able to fully test this PR yet.

**Comment by michellema1208** [comment]
@thelostone-mc it looks like the build for Builder specifically is still queued, so am not able to test atm!

**Comment by thelostone-mc** [comment]
@michellema1208 this looks like this was added to the grant-explorer instead of the builder :/

**Comment by boudra** [comment]
@thelostone-mc @michellema1208 what do we do here? are we moving this change to the Builder or shall we merge this?

**Comment by thelostone-mc** [comment]
I would say this ticket needs to be added to the backlog and taken up !
Defer to @michellema1208 if this makes sense to have on the explorer side as well (that's what this PR does)

**Review by michellema1208 — CHANGES_REQUESTED** [review]
@thelostone-mc - there's two issues I'm finding after testing this change on Explorer: 

- [ ] The date that's being pulled in is the Application End date, not the Application Start Date 
- [ ] The date and time needs to have a space in between to be human-readable 

Screen Shot 2023-06-02 at 9 03 30 AM

@thelostone-mc - I defer to you if you want to make these fixes. If you don't have bandwidth, we can archive this PR as these changes on Explorer were never in scope to begin with.

**Comment by michellema1208** [comment]
Per conversation with @nfrgosselin (https://discord.com/channels/562828676480237578/1113121406360756264/1114220973491765299) - we're going to close this PR as the changes are out of scope. I'm going to close this PR so we know not to merge it.

**Pull request closed without merging**
