### PR TITLE
1529 - add preview copy message

### LINKED ISSUE #1529: Builder: Add more copy that the Application Preview page is what the project will look like on Explorer
**User story**
As a project owner, 
I want to understand what I'm looking at when I'm on the Application Preview page 
so that I can make any edits accordingly 

**Acceptance Criteria**
GIVEN that I am on the Application Preview page
WHEN I look at the page
THEN I see a message explaining to me that this is a preview of what my project will look like on Explorer 

**Product & Design links**
* [Figma](https://www.figma.com/file/U4uRlyJJn92QiNUuyRxSvX/%5BWIP%5D-Grants-Application-%2F-Edit-Flow?type=design&node-id=647-5313&t=Mblf4FQ6fXkAhDM0-0)

### PR DESCRIPTION
**Pull request by codenamejason**
closes #1529 

Screenshot 2023-05-25 at 11 32 29 AM

### CODE REVIEW

**Comment by michellema1208** [comment]
@codenamejason - I tested using this deploy link (https://bafybeif5ricqxgzraxb7zplzpvp66y4pblrufklrjz6p7b2bwqwetmixvm.on.fleek.co/) that I grabbed from above, but am not seeing the preview page copy changes.

Screen Shot 2023-05-23 at 1 31 10 PM

**Comment by codenamejason** [comment]
@michellema1208 it's stuck...
Screenshot 2023-05-23 at 1 33 09 PM

**Review by michellema1208 — CHANGES_REQUESTED** [review]
hey @codenamejason - two minor things: 

- [ ] The message should _only_ show up on the Preview step, not on the previous pages (selecting your project, filling out your application) 

Screen Shot 2023-05-25 at 3 31 18 PM
Screen Shot 2023-05-25 at 3 31 33 PM

**Review by KurtMerbeth — APPROVED** [review]

**Review by michellema1208 — APPROVED** [review]
LGTM - great work Jason!

**Pull request merged**
