### PR TITLE
Edit flow integration

### LINKED ISSUE #1646: Manager: track all changes made to a round and have it stored in state
**User Story:**
As a program manager
I want to be able to edit my round details
So that I can make necessary changes before the round starts

**Acceptance Criteria**
GIVEN that I am on my Round Settings tab AND the round voting period hasn't started yet
WHEN I click the Edit Round button
THEN all the round details components switch to their editable state
AND the Edit Round button is replaced by the Cancel and Update Round buttons

GIVEN that I am on the Round Settings tab in the editable state
WHEN I click Cancel
THEN all the round details components switch back to their uneditable state
AND the Cancel/Update Round buttons are replaced by the Edit Round button

GIVEN that I am on the round settings tab in the editable state AND have made changes to my settings
WHEN I click "Update Round"
THEN I see the Update Round modal
AND it tells me how many transactions I will need to sign to make the changes

GIVEN that I am looking at the Update Round modal
WHEN I click Cancel
THEN the modal closes and I return to the editable state

**Product & Design Links:**
[Figma](https://www.figma.com/file/guY5OKIgM18SNa62OysBoe/%5BWIP%5D-Linear-QF-Flow-v2?node-id=143-9624&t=oaaQsqSd6tVU7JGu-4)
[Loom of UX](https://www.loom.com/share/30521a647d074d49a7bc306809fbe450)

**Tech Details**

As a round operator, when I should be able to 
- enable edits on all the fields across the tabs  
- make changes to the form 

From the dapp side , the dapp should be able to 
- keep track of which all fields have been changed
- store them in the state

End Result: You should be able to console log the state and show which all fields have been updated

### PR DESCRIPTION
**Pull request by codenamejason**
Closes #1646 #1701

### CODE REVIEW

**Comment by michellema1208** [comment]
@thelostone-mc @codenamejason @DanieleSalatti - I believe I was just able to test the integration branch, and found a couple of things we need to fix. I recorded a Loom overview, and I'll also callout tasks below, broken down by each tab. 

Loom Overview: https://www.loom.com/share/23bcca3612974748b6f361230d368cab 

### General 

- [ ] The "Edit Round" button border disappears on hover - I believe we want the border to still be there but just a lighter color, similar to the "View on Explorer" button behavior. + @willsputra to confirm! 
- [ ] For all fields, once we are in edit mode, the text color should be black, not light gray. This signals that the text is ready to be edited. Otherwise, it looks like we're still in view-only mode. + @willsputra to confirm! 
- [ ] It looks like the second time that I switch tabs, the screen goes blank and I need to refresh the page, and once I refresh I need to navigate back to Round Settings, and re-enter edit mode again. This happened towards the end of my Loom recording. This happens even if I'm not in edit mode. 

### Round Details tab 

- [ ] Missing the ability to remove round eligibility requirements (see Figma) 
- [ ] Missing the ability to add new round eligibility requirements (see Figma) 

### Round & Application Period tab 

- [ ] The color of time in UTC should be a lighter gray (see Figma) // + @willsputra to confirm 
- [ ] When I select a date, it should close the date picker window and update to new date - same as on Round Creation flow 
- [ ] I should only be able to select dates and times on current and future days (I can currently select dates in the past) 
- [ ] Dates in the future should have be a darker color on date picker - same as on Round Creation flow  // + @willsputra to confirm 

### Funding Settings tab 

- [ ] I can't change my YES/NO selection for any question with radio select button (matching cap, minimum donation threshold, sybil defense 
- [ ] I am able to edit the field for matching cap + minimum donation questions even if I selected "NO" - they should only be editable if I change my answer to "YES" or if I had selected "YES" already

**Comment by willsputra** [comment]
> The "Edit Round" button border disappears on hover - I believe we want the border to still be there but just a lighter color, similar to the "View on Explorer" button behavior. + @willsputra to confirm!

It seems like right now the "View on Explorer" button border also disappears, although it has a light drop shadow so it appears as a "border". If you look at the Round Applications tab, the buttons' borders (and bg) disappear too. I'd say this isn't a blocker for this ticket, but we can create another ticket to define buttons' behavior in general? I'd also love to jam with Melissa first on this. Wdyt @michellema1208 ?

> For all fields, once we are in edit mode, the text color should be black, not light gray. This signals that the text is ready to be edited. Otherwise, it looks like we're still in view-only mode. + @willsputra to confirm!

Agree! It should look like active inputs on the round creation flow (with black font)

> The color of time in UTC should be a lighter gray (see Figma) // + @willsputra to confirm

Yep! Altho not a blocker for now if it takes a lot of effort to do this.

>  Dates in the future should have be a darker color on date picker - same as on Round Creation flow // + @willsputra to confirm

Yep! The date picker generally should behave the same way as on the round creation flow.

------

Also adding a few more UI fixes:

**General**
- [ ] Add the edit icon on Edit Round button
image

- [ ] We don't need to make the input labels bold, use regular font weight like we do during Round Creation

**Funding Settings tab**
- [ ] Add '%' on Matching Cap "If so, how much?" input
- [ ] Add 'USD' on Minimum Donation Threshold "If so, how much?" input
- [ ] Add light gray background on 'A single project can only receive...' and 'Each donation has to be a minimum...' info
image

thanks @codenamejason @DanieleSalatti !

**Comment by codenamejason** [comment]
@michellema1208 and @willsputra this is the wrong branch is why all the issues stated above. We will be updating this branch with the `edit-flow-error-states` branch, PR #1758. I apologize for the misunderstanding and will update when it can be reviewed.

**Comment by willsputra** [comment]
thanks for this @codenamejason! I've put checkmarks on the previous comment for the things that have been addressed. :)

feedback for the latest preview link: 

**Round Details tab** 

- [ ] When I click Edit Round, then edit the round name, and click Cancel -> the new round name shows up. It should show the original round name when I click cancel.

**Funding Settings tab**

- [ ] When I click Edit Round, then edit the radio buttons on Matching Cap / Min Donation Threshold / Sybil, and click Cancel -> the active radio button indicators are gone. The original settings should show up when I click cancel.

image

**Comment by michellema1208** [comment]
@thelostone-mc @codenamejason @DanieleSalatti - here are bugs I've found on my second pass of testing: 

### General 

- [ ] When in edit mode, the text in all fields should be black (just like active inputs in the Round Creation flow) 
- [ ] Missing required/optional labels on all text fields (see Figma) 

### Round Details tab 

- [ ] Missing border around answer to "Program Chain" question (see Figma) 

### Round & Application Period tab 

- [ ] The color of time in UTC should be a lighter gray - both in read-only and edit mode (see Figma) 
- [ ] In read-only mode, each field should have the right labels (start date, end date) 
- [ ] Too much top padding on each field once in edit mode (+ @willsputra to follow up with correct padding amount) 
- [ ] Dates in the future should have be a darker color on date picker - same as on Round Creation flow  
- [ ] Missing the validation check to make sure application end date is _before_ round start date

### Funding Settings tab 

Recorded a Loom for this tab in particular: https://www.loom.com/share/ba34583bbbbc4034b9935b8441231ccd 

- [ ] Too much right padding on the token (ETH, DAI) / % / USD labels (+ @willsputra to follow up with correct padding amount) 

- [ ] Tooltips are not working (nothing happens when I mouse over) 

- [ ] If I click "Edit" and for the matching cap question I select "Yes" > click on the field > select "No" > click "Update Round", I'm getting this error. This behavior should not trigger an error at all, as in the end I'm keeping my selection as "No" 
Screen Shot 2023-05-12 at 12 16 06 PM

- [ ] If I edit the matching cap field by selecting Yes > inputting a percentage > hit Cancel -> the percentage stays even though the selection resets to No (shown in Loom) 

- [ ] In read-only mode, on the Sybil Defense question, it says I've selected neither Yes or No, when I have selected Yes when setting up the round (shown in Loom). You can see my selection once I enter Edit mode. 

- [ ] Whenever I try to edit the matching cap %, I get this error: 
Screen Shot 2023-05-12 at 12 22 58 PM

- [ ] The calculation of the matching funds based on matching cap % is wrong (it was saying 1% matching cap equals 100 ETH, when total matching funds available is 100 ETH)

**Comment by willsputra** [comment]
> In read-only mode, each field should have the right labels (start date, end date)
 > Too much top padding on each field once in edit mode (+ @willsputra to follow up with correct padding amount)

The fields that we use on round creation flow look right. maybe we can reuse those?
image

> Too much right padding on the token (ETH, DAI) / % / USD labels (+ @willsputra to follow up with correct padding amount)

12px!

**Comment by michellema1208** [comment]
hey @codenamejason @KurtMerbeth @thelostone-mc - sharing notes from my third pass on testing: 

Note: I intentionally did not test editing the "Eligibility Requirements" section, as Jason noted that there were still some existing bugs. 

### General 

- [ ] When I click "Update", nothing happens anymore (not sure if this is intentional / waiting for changes to be merged) 

### Application & Round Period tab 

- [ ] When a date has passed, that field should be read-only/not editable. I'm currently getting an error for a past application start date, when I shouldn't be able to edit it in the first place: 
Screen Shot 2023-05-15 at 7 17 11 PM

### Funding Settings

- [ ] If my selection to matching cap % was "No", and I change it to "Yes", I can't edit the value of matching cap 

FYI @thelostone-mc I did find some UX differences, but since none were critical and to keep us moving forward, I extracted them into this follow-up ticket (https://github.com/gitcoinco/grants-stack/issues/1804). I defer to you if you think we should address them in this PR, or keep it in a follow-up ticket.

**Comment by DanieleSalatti** [comment]
> When a date has passed, that field should be read-only/not editable. I'm currently getting an error for a past application start date, when I shouldn't be able to edit it in the first place

I started looking into this, and while the component docs say that it can be made uneditable using the `isValidDate` function like this:

```
isValidDate={(current) => {
    return (
      disablePastAndBeforeRoundStartDate(current) &&
    round.applicationsStartTime > new Date()
  );
}}
```

...it doesn't fully work. 

The dates are all non-selectable, but you can still change the time... 🫤 I can work around this tomorrow by conditionally changing the style of the input component that we use in read-only mode so it looks like a disabled date-picker when we switch to edit.

**Comment by michellema1208** [comment]
@codenamejason @KurtMerbeth @thelostone-mc : here are the bugs that I found in my fourth round of testing: 

Loom overview: https://www.loom.com/share/79e521f5d91d4ce3bb3e39dfccc7af8e 

### General 
- [ ] After I edit a round and click "Update", I can no longer scroll on any of the pages in Manager unless I refresh the page

### Application & Round Period tab 
- [ ] When a date has passed, I can still edit the field to select a date in the future -> the field should be disabled/read-only if the date has passed

### Funding Settings
- [ ] If I'm still in the process of editing my value for matching funds, don't throw this error - this error should only be thrown if I try to update the round with a blank field 
Screen Shot 2023-05-16 at 11 40 04 AM

- [ ] If my selection to matching cap % was "No" and the field was set to 0, when I change it to "Yes", I can't delete the 0

- [ ] If my selection to Minimum Donation Threshold was "No" and the field was set to 0, when I change it to "Yes", I can't delete the 0 and it moves the field

**Comment by michellema1208** [comment]
@codenamejason @KurtMerbeth @thelostone-mc 

one other bug I found, forgot to write this in my above comment: 

- [ ] Missing the ability to remove eligibility requirements (see Figma)

**Comment by hmrtn** [comment]
See: https://github.com/gitcoinco/grants-stack/pull/1805#issuecomment-1552027898

**Review by bhargavaparoksham — CHANGES_REQUESTED** [review]
1. If i edit the application start date & update it to a date greater that round start date or round end date it doesn't show any error.
2. Tests for UpdateRoundContext are missing.

**Comment by michellema1208** [comment]
@codenamejason @KurtMerbeth (cc: @thelostone-mc ): thank you for all of your hard work here!!!! This is looking WAY better, super stoked about it. 

The **only** remaining bug is the following: 

- [ ] The donation field moves when any of the other fields have an error
Screen Shot 2023-05-18 at 3 08 02 PM

To me, it seems like what's causing the bug is the errors that we display on the above two fields - if there's a way to lock this field in place even when there are errors on above input fields, that would be great.

**Comment by KurtMerbeth** [comment]
> * More of a question: why can't we remove the 0 input? Given that it's a free text field, I would expect to be able to remove the 0.

fixed

**Review by michellema1208 — APPROVED** [review]
amazing work here @codenamejason @KurtMerbeth ! This overall resolves most of the major bugs we were seeing, and I'd love to give you guys the greenlight to merge this integration branch. 

For transparency, I did find some minor bugs around matching cap percentage that I pulled into a separate ticket here (https://github.com/gitcoinco/grants-stack/issues/1841). My thinking is that it would be easier for us to merge this integration branch first as it's likely getting pretty large, and then resolve the additional bugs that I found after. Ultimately defer to @thelostone-mc here if he has any preferences

**Review by thelostone-mc — APPROVED** [review]
Just tested this locally. LGTM

**Pull request merged**
