### PR TITLE
cart revamp

### PR DESCRIPTION
**Pull request by thelostone-mc**
image

Fixes https://github.com/gitcoinco/grants-stack/issues/3276

### CODE REVIEW

**Review by bhargavaparoksham — APPROVED** [review]
lgtm.

**Review by melissa-neira — CHANGES_REQUESTED** [review]
A few things here on the right hand side - 
in staging:
Screenshot 2024-04-15 at 16 26 05
in figma: 
Screenshot 2024-04-15 at 16 27 40

- the right side column should have a 24px border radius
- there should be no drop shadow for the submit donation button
- font sizing and weights feel off throughout the cart, please double check that in figma
- there's something weird going on with the gray box and the blue button, they don't seem fully connected (my guess is that the drop shadow is making that apparent, please remove)
- also, the font color for matching estimates in the round carts should be #11BC92 (green/teal)

**Review by codenamejason — APPROVED** [review]

**Review by michellema1208 — COMMENTED** [review]
deferring to @melissa-neira on final approval as these are primarily UX/branding changes!

**Comment by codenamejason** [comment]
Screenshot 2024-04-15 at 12 34 40 PM

**Review by melissa-neira — APPROVED** [review]
lgtm!

**Pull request merged**
