### PR TITLE
Add support for scroll mainnet

### PR DESCRIPTION
**Pull request by bhargavaparoksham**
Fixes: #2837 

## Description

Add support for scroll mainnet

## Checklist

This PR:

- [ ] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [ ] Doesn't disable eslint rules.
- [ ] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [ ] Doesn't contain commented out code.
- [ ] If adding/updating a feature, it adds/updates its test script on Notion.

### CODE REVIEW

**Review by boudra — APPROVED** [review]

**Comment by michellema1208** [comment]
hey @bhargavaparoksham - I'm blocked currently from applying to a round, for both rounds with email encryption and without. I'm assuming this will be resolved once the separate Lit PRs are merged, but sharing FYI! 

Screen Shot 2024-02-01 at 2 52 03 PM

No email round: https://builder-git-scroll-2837-grants-stack.vercel.app/#/chains/534352/rounds/0x63e2270803e4d175226886dcb024faac2ecbf83a/apply 

Email round: https://builder-git-scroll-2837-grants-stack.vercel.app/#/chains/534352/rounds/0xbb5c1eb31b9e7b9f22e36f483a79139962ee03fc

**Comment by michellema1208** [comment]
hey @bhargavaparoksham - the only functionality that's not working for me is being able to decrypt application questions - I'm still seeing N/A after I sign in: 

Screen Shot 2024-02-02 at 2 29 29 PM

Link: https://manager-git-scroll-2837-grants-stack.vercel.app/#/round/0xc627bf70068f8b5513dd6af6dedd02aea0e3583c/application/0xc627bf70068f8b5513dd6af6dedd02aea0e3583c-0

**Comment by michellema1208** [comment]
@bhargavaparoksham - it looks like donations from Scroll are still missing from the Donation History page: https://explorer-git-scroll-2837-grants-stack.vercel.app/#/contributors/0x37e5e6eb36467F98392ebBb35F110FbB8238e6D3

**Comment by gravityblast** [comment]
@bhargavaparoksham I created a round with this tx but it doesn't show up in Manager under its program:

https://scrollscan.com/tx/0x64de5a9cd1074226d12a204d285f68c2e10d02c155e5f5eac0608aa830f45b27

**Review by gravityblast — APPROVED** [review]

**Review by michellema1208 — APPROVED** [review]

**Pull request merged**
