### PR TITLE
3301/Thank you page updates

### PR DESCRIPTION
**Pull request by codenamejason**
Fixes: #issue

## Checklist

This PR:

- [x] Does it add new payout or donation token? In this case, have they been added to the indexer to avoid it to crash?
- [x] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [x] Doesn't disable eslint rules.
- [x] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [x] Doesn't contain commented out code.
- [x] If adding/updating a feature, it adds/updates its test script on Notion.

### CODE REVIEW

**Comment by 0xKurt** [comment]
@codenamejason can we rename the functions which return the SVG's, like `Builder()`, and add the term `Icon` to it? e.g. `BuilderIcon()`

**Review by thelostone-mc — APPROVED** [review]

**Review by 0xKurt — APPROVED** [review]

**Review by michellema1208 — COMMENTED** [review]
Testing on behalf of Melissa this week as she's OOO! 

From my testing, it looks like the Thank You page looks a bit different in development vs. designs. 

**In Development:** 
Link: https://explorer-git-thankyou-grants-stack.vercel.app/#/thankyou

Screen Shot 2024-04-22 at 3 30 38 PM

**Designs:** 
[Link to Figma](https://www.figma.com/file/c4UCPzbLnK3kz67M6R9VGN/Explorer-S20?type=design&node-id=468-4277&mode=design&t=knpWXp7zML80OHe6-0)

Screen Shot 2024-04-22 at 3 30 51 PM

**My observations:** 
- It looks like the background image on the Thank You page in development is more zoomed in than in designs -- as a result, it looks noisier 
- It looks like in Melissa's designs, the text overlay sits on top of the gradient, not the background image, which gives it a cleaner look 

The caveat here is that I might be missing some context on either Design or Engineering side! Feel free to merge without my approval if that's the case.

**Comment by codenamejason** [comment]
Yeah, we had a Discord chat about this: https://discord.com/channels/562828676480237578/1230272053035401366

Thank you for reviewing 🙏🏻

**Comment by michellema1208** [comment]
@codenamejason ah got it, yes I definitely missed that thread! Sounds good - if Melissa is on board, I am too! TY for merging :)

**Pull request merged**
