### PR TITLE
[1840] Manager: allow applications and round period to overlap

### LINKED ISSUE #1840: Manager: allow applications and round period to overlap
**User Story:**
As a Program Manager
I want to accept applications even after my round has started 
So that I don't exclude qualified projects based on application timeline

**Acceptance Criteria**
GIVEN that I am creating a round
WHEN I am configuring application and round dates 
THEN I see a checkbox to accept applications throughout the round 

GIVEN that I want to accept applications throughout the round 
WHEN I check the box 
THEN I see the application end date field is read-only 
AND it populates based on the round end date selection 

**Product & Design Links:**
- [Loom walkthrough](https://www.loom.com/share/0088cad637a14e86bbbda735a32da47b)
- [Figma](https://www.figma.com/file/V113F2Pp5m2qDM5odXjfFu/Manager-S17?type=design&node-id=2058%3A44553&t=72M3DAIH6udXhBQJ-1)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

### PR DESCRIPTION
**Pull request by DanieleSalatti**
### Description

Changes round creation behaviour as per [Figma](https://www.figma.com/file/V113F2Pp5m2qDM5odXjfFu/Manager-S17?type=design&node-id=2058%3A44553&t=72M3DAIH6udXhBQJ-1) and [Loom walkthrough](https://www.loom.com/share/0088cad637a14e86bbbda735a32da47b).
@willsputra I added a tooltip as well, let me know if you want me to remove it.

### Refers/Fixes

Fixes #1840

### CODE REVIEW

**Review by michellema1208 — CHANGES_REQUESTED** [review]
@DanieleSalatti - overall this looks great! One minor UX change from my side, see Loom: https://www.loom.com/share/33623c5dc689411abcf506080e34b2cd

**Comment by DanieleSalatti** [comment]
> @DanieleSalatti - found a minor edge case, documented in this Loom: https://www.loom.com/share/a8cc010eaba34e01a45af104bbee6c53

Nice catch!

**Review by bhargavaparoksham — APPROVED** [review]
@DanieleSalatti round manager build is failing. Other than that code wise LGTM.

**Comment by vacekj** [comment]
## PR checklist

For every PR, make sure that these statements are true:
- [ ] Branch is rebased on latest main
- [ ] Includes only changes relevant to the original ticket. Refactoring and formatting needs to be separated.
- [ ] Doesn't contain `any`
- [ ] Doesn't contain unnecessary type casts and non-null asserts
- [ ] Doesn't add `@ts-ignore`
- [ ] Doesn't disable lints
- [ ] Doesn't use `useState` just for computation
- [ ] Splits components into pure components that don't depend on external state or hooks.
- [ ] Doesn't add components inside of components that depend on variables in the parent scope
- [ ] Doesn't propagate optional values without good reason
- [ ] Doesn't duplicate existing code
- [ ] Validates out-of-domain data
- [ ] Does things as simple as possible, but not simpler.
- [ ] Doesn't reinvent the wheel or create premature and unnecessary abstractions.
- [ ] Doesn't contain commented out code.
- [ ] Doesn't contain skipped or empty tests.
- [ ] Is properly formatted.

**Comment by DanieleSalatti** [comment]
@michellema1208 I need your approval to merge this.

> "If a collaborator with admin, owner, or write access to the repository submits a review requesting changes, the pull request cannot be merged until the same collaborator submits another review approving the changes in the pull request."

**Review by michellema1208 — APPROVED** [review]

**Review by vacekj — APPROVED** [review]

**Pull request merged**
