### PR TITLE
Create Allo v2 Round

### PR DESCRIPTION
**Pull request by boudra**
fixes https://github.com/gitcoinco/grants-stack/issues/2870

## How to test

1. Use the manager-staging preview to test allo v2 (NOT manager)
2. Ensure you are on Allo v2 by checking the footer
3. Ensure you have a program (profile) created
4. Trying to create a program on V2 will show up a message saying to go to Builder
5. If you don't have a program created, go to Builder staging to create it (https://grants-stack-builder-staging.vercel.app/#/projects), then come back to Manager (in Allo v2 a project is a program)
6. You should see your program now
7. Create a QF or DG round using Allo V2, only testnets should work (I am testing on Mumbai)
8. You should see the round you created in the list of rounds for the program
9. In the round list, verify that the round appears with the correct title, dates
10. QF rounds should have a QF badge. DG rounds are still not indexed properly and will not have a badge, waiting on this PR: https://github.com/gitcoinco/grants-stack-indexer/pull/451

Notes:

- Clicking the round itself to see the round page will not work yet, this is being done here: https://github.com/gitcoinco/grants-stack/pull/2935

## Checklist

This PR:

- [x] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [x] Doesn't disable eslint rules.
- [x] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [x] Doesn't contain commented out code.
- [x] If adding/updating a feature, it adds/updates its test script on Notion.

### CODE REVIEW

**Review by bhargavaparoksham — CHANGES_REQUESTED** [review]
Round creation on polygon is failing with the following error.

`AlloError: Failed to send raw transaction: Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0xc24e3C2e72f960fa1d54170Fa03492DDa4cE8256","to":"0x1133eA7Af70876e64665ecD07C0A0476d09465a1","data":"0x77da8caf229346be27f09a1570e04cc48b6ff5c01ef8902ea44182a16adcaf7f1a6b3d27000000000000000000000000d13ec67938b5e9cb05a05d8e160daf02ed5ea9c900000000000000000000000000000000000000000000000000000000000000e00000000000000000000000003c499c542cef5e3811e1192ce70d8cc03d5c33590000000000000000000000000000000000000000000000000000000005f5e100000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002e000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000065d365e80000000000000000000000000000000000000000000000000000000065dfc9000000000000000000000000000000000000000000000000000000000065d3eb80000000000000000000000000000000000000000000000000000000006608a78000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000003b6261666b7265696179786464666368376e786465696d7975696b7437716d6a613562666d77676d7469726c7278643569376475746c6562677a666100000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000c24e3c2e72f960fa1d54170fa03492dda4ce8256","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted","data":"0x93699238","cause":null}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)`

Screenshot 2024-02-19 at 7 38 19 PM

**Comment by boudra** [comment]
> Round creation on polygon is failing with the following error.
> 
> `AlloError: Failed to send raw transaction: Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0xc24e3C2e72f960fa1d54170Fa03492DDa4cE8256","to":"0x1133eA7Af70876e64665ecD07C0A0476d09465a1","data":"0x77da8caf229346be27f09a1570e04cc48b6ff5c01ef8902ea44182a16adcaf7f1a6b3d27000000000000000000000000d13ec67938b5e9cb05a05d8e160daf02ed5ea9c90000000000000000000000000000000000000000000002e72f960fa1d54170fa03492dda4ce8256","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted","data":"0x93699238","cause":null}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)`
> Screenshot 2024-02-19 at 7 38 19 PM

@bhargavaparoksham Allo v2 only works in testnets for now

**Comment by vacekj** [comment]
image

**Comment by boudra** [comment]
> image

lol 2.4k lines changed is only the pnpm-lock.yml

**Comment by melissa-neira** [comment]
@boudra I'm not sure if I can test this - idk why but I don't have any programs made (I should), so I can't create a round. when I do go to try to make a program, it seems like everything goes through but the program I made doesn't show up.
this is the screen I get after trying to make a program... not sure if this is related at all to this PR (prob not) but wanted to give you a heads up just in case
Screenshot 2024-02-19 at 16 20 02

**Review by vacekj — APPROVED** [review]

**Comment by vacekj** [comment]
confirming same issue as Melissa @boudra, I can't see any programs I create on Mumbai or PGN Testnet. Round creation fails on OP Mainnet but I guess that's expected
image

**Comment by boudra** [comment]
@vacekj @melissa-neira programs (or profiles as they are called in Allo v2) are created in builder, we don't create programs in manager as the task describes, programs in allo v1 also do not exist in allo v2 and to test v2 you have to switch to Allo v2 by using the button in the footer.

I will update the PR description with a step-by-step guide to test this.

**Comment by boudra** [comment]
Let me know if you still see issues! thanks for testing 🙂

**Comment by boudra** [comment]
> @boudra ok so I was able to test, but then ran into a problem when deploying the round. first, there was an "unknown error" (I'll attach the screenshot) and so I tried the txn again, and the round was deployed. except, now there are 2 identical rounds deployed. not sure now this happened!
> 
> error: Screenshot 2024-02-19 at 17 37 58
> 
> after round was deployed: Screenshot 2024-02-19 at 17 39 05

awesome thanks for the feedback, looking into it!

**Comment by michellema1208** [comment]
hey @boudra - running into an issue on step 2: when I switch to Allo v2 on Manager staging, I'm getting a blank page. Screenshot of console error logs: 

Screen Shot 2024-02-20 at 9 24 33 AM

**Comment by bhargavaparoksham** [comment]
@boudra i'm seeing a bug where even though if the application period has not started. In the round page its showing applications in progress.
eg: https://manager-staging-git-create-v2-round-grants-stack.vercel.app/#/round/0xf9b06ce868e2c746394e6cd4e89539d72b2e26c0

Screenshot 2024-02-20 at 8 03 26 PM

**Comment by boudra** [comment]
> @boudra i'm seeing a bug where even though if the application period has not started. In the round page its showing applications in progress. eg1: https://manager-staging-git-create-v2-round-grants-stack.vercel.app/#/round/0xf9b06ce868e2c746394e6cd4e89539d72b2e26c0
> 
> eg2:https://manager-staging-git-create-v2-round-grants-stack.vercel.app/#/round/0x3dc117682ad2a5246c09bb077f7a75d38fb9fc6d?debug=true
> 
> Note that this v1 round. Another adjacent issue is i'm not able to open this round in builder.
> Screenshot 2024-02-20 at 8 17 05 PM

I am not sure that the issue was introduced by this PR, but I have fixed it anyways.

**Review by melissa-neira — APPROVED** [review]
I was able to create a round! wooohooo!😎

**Review by michellema1208 — COMMENTED** [review]
@boudra - confirming that creating a QF and DG round works, but it seems like incorrect dates are showing up. 

Here are the dates I set for my DG round: 
Round: https://manager-staging-git-create-v2-round-grants-stack.vercel.app/#/round/17 

Screen Shot 2024-02-20 at 11 11 56 AM

Here are the dates I set for my QF round: 
Round: https://manager-staging-git-create-v2-round-grants-stack.vercel.app/#/round/18 

Screen Shot 2024-02-20 at 11 13 37 AM

Here's what I'm seeing on my round list: 
Program: https://manager-staging-git-create-v2-round-grants-stack.vercel.app/#/program/0x63d017f85258a80d6ffa1ed9681820731b1db904a4812fbf70b5d378983b2430 

Screen Shot 2024-02-20 at 11 14 46 AM

A couple callouts: 
* It looks like for QF rounds, there seems to be a +5 hour difference
* It looks like for DG rounds, both dates and time are not right 
* For DG rounds, there shouldn't be an "application" period -- should only be a round period (compare against prod rounds)

**Comment by boudra** [comment]
@michellema1208 the dates look like an indexer issue, looking into it now.

DG rounds show an application date because they're still not indexed properly as DG (same issue as the badge), once that is done they will disappear.

It's safe to merge this PR as those issues are indexer related, they can be fixed in parallel and Allo V1 should not be affected.

**Review by bhargavaparoksham — APPROVED** [review]

**Review by michellema1208 — APPROVED** [review]

**Pull request merged**
