### PR TITLE
gg19 cleanup

### PR DESCRIPTION
**Pull request by bhargavaparoksham**
Fixes: #2694 

- [x] Hide Projects tab 
- [x] Hide Collections
- [x] Hide Categories 
- [x] Remove GG19 Live stats button 

## Checklist

This PR:

- [x] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [x] Doesn't disable eslint rules.
- [x] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [x] Doesn't contain commented out code.
- [x] If adding/updating a feature, it adds/updates its test script on Notion.

### CODE REVIEW

**Review by melissa-neira — APPROVED** [review]
lgtm!

**Review by bard — COMMENTED** [review]
The PR description says "hide collections" and "hide categories", but the code removes them.

Are collections and categories intended to come back at some point, in which case they could be conditionally disabled with a flag, or will they be gone for good, in which case the purpose is indeed to remove (rather than hide) them?

**Comment by vacekj** [comment]
@bhargavaparoksham +1 to bard's question, @gitcoinco/grantsstack-product could shine a light here maybe.

**Comment by meglister** [comment]
> @bhargavaparoksham +1 to bard's question, @gitcoinco/grantsstack-product could shine a light here maybe.

These specific collections/categories will likely not come back. We may use collections and categories again in the future -- though for collections especially, I think we will likely re-work how they are configured. Knowing that, do you think it's best to remove or hide?

**Review by bard — APPROVED** [review]

**Comment by vacekj** [comment]
re @meglister in this case, we can proceed with how this PR is done. approved.

**Review by vacekj — APPROVED** [review]

**Pull request merged**
