### PR TITLE
Explorer: [2569] Hide test and spam rounds

### LINKED ISSUE #2569: Explorer: manually hide some test / spam rounds on Explorer Homepage for GG19
**Overview**
Let's hide some of the test / spam rounds we're seeing on the Explorer Homepage ahead of GG19. 

**Details**

Hide the following rounds: 
- [ ] DO NOT USE: https://explorer.gitcoin.co/#/round/10/0x7c1104c39e09e7c6114f3d4e30a180a714deac7d 
- [ ] 1inch LATAM GG19 (duplicate round): https://explorer.gitcoin.co/#/round/10/0x79715bf10dab457e06020ec41efae3484cff59dc 
- [ ] Token Engineering (deployed on OP): https://explorer.gitcoin.co/#/round/10/0x4632ea15ba3c1a7e072996fb316efefb8280381b 
- [ ] For the commercial: https://explorer.gitcoin.co/#/round/10/0xfe36ff9c59788a6a9ad7a979f459d69372dad0e6 
- [ ] Lineabot: https://explorer.gitcoin.co/#/round/1/0xa7149a073db99cd9ac267daf0c4f7767e50acf3f
- [ ] Linnie Franney: https://explorer.gitcoin.co/#/round/42161/0x4abc6f3322158bcec933f18998709322de7152c2
- [ ] Shadow NFTs: https://explorer.gitcoin.co/#/round/10/0xae53557089a1d771cd5cebeaf6accbe8f064ff4c 
- [ ] great geese: https://explorer.gitcoin.co/#/round/424/0xee3ed186939af2c55d33d242c4588426e368c8d0
- [ ] great geese (duplicate): https://explorer.gitcoin.co/#/round/424/0x8011e814439b44aa340bc3373df06233f45e3202 
- [ ] TyVy zero: https://explorer.gitcoin.co/#/round/10/0xf3cd7429e863a39a9ecab60adc4676c1934076f2 
- [ ] Aribitrum One Test Round: https://explorer.gitcoin.co/#/round/42161/0x88fc9d6695bedd34bbbe4ea0e2510573200713c7 
- [ ] PowerPool Test Round: https://explorer.gitcoin.co/#/round/10/0xae18f327ce481a7316d28a625d4c378c1f8b03a2
- [ ] GMX Test: https://explorer.gitcoin.co/#/round/137/0x9b3b1e7edf9c5eea07fb3c7270220be1c3fea111 
- [ ] GMX Test 2: https://explorer.gitcoin.co/#/round/137/0x4c19261ff6e5736a2677a06741bf1e68995e7c95

### PR DESCRIPTION
**Pull request by carlbarrdahl**
- Fixes #2569 

## PR checklist

For every PR, make sure that these statements are true:
- [x] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [x] Doesn't contain type casts and non-null assertions.
- [x] Doesn't add `@ts-ignore`.
- [x] Doesn't disable lints.
- [x] Doesn't use `useState` just for computation - use plain variables instead.
- [x] Splits components into pure components that don't depend on external state or hooks.
- [x] Avoid embedding components within other components
- [x] Doesn't propagate optional values without good reason, doesn't mark property values as optional if that doesn't represent reality.
- [x] Doesn't duplicate existing code.
- [x] Parses out-of-domain data - this includes user input, API respones, on-chain data etc.
- [x] Doesn't contain commented out code.
- [x] Doesn't contain skipped or empty tests.
- [x] If this PR adds/updates any feature, it adds/updates its test script

Subjective - at the discretion of the reviewers
- Does things as simply as possible, but not simpler.
- Doesn't reinvent the wheel or create premature abstractions.

##### Refers/Fixes

fixes #issuenumber

### CODE REVIEW

**Comment by vacekj** [comment]
@carlbarrdahl I see that one of the tests is failing, this is due to JSDom being different an actual browser dom, and an `instanceof` typecheck failing in one of the libraries, therefore `getAddress` fails too. I solved this in the past by polyfilling the Uint8Array, and it seems it is getting polyfilled in `setupTests.ts`, but you may also want to try this one: https://github.com/paralleldrive/cuid2/issues/44#issuecomment-1531731695

**Review by bhargavaparoksham — APPROVED** [review]

**Review by melissa-neira — COMMENTED** [review]
@carlbarrdahl still seeing some test rounds:
Screenshot 2023-11-13 at 12 16 58

**Comment by carlbarrdahl** [comment]
> @carlbarrdahl still seeing some test rounds: Screenshot 2023-11-13 at 12 16 58

Are any of these rounds the ones mentioned in the issue?
- https://github.com/gitcoinco/grants-stack/issues/2569

They seem to be removed in the production environment:
- https://explorer-git-2569-hide-spam-rounds-grants-stack.vercel.app/#/?skip_redirect=true

**Review by melissa-neira — APPROVED** [review]
@carlbarrdahl cool, yeah I'm not seeing any of those in the prod envi. lgtm!

**Pull request merged**
