### PR TITLE
[1528] add/fixed verified badges, created, payout address, cropped banner

### LINKED ISSUE #1528: Builder: Application Preview page missing verifications and copy
**Overview**

The Application Preview page is currently missing the following: 
- [x] Verified badges for verified project socials (on Twitter and Github organization) 
- [x] The "Created: <Date>" (missing "Created:") 
- [x] Payout Wallet Address and icon 
- [x] Banner image is cropped (should preview close to the same size it will show up on the Explorer) 

**Currently:**
Screen Shot 2023-04-20 at 1 38 08 PM

**Figma:**
Screen Shot 2023-04-20 at 1 55 01 PM

* [Figma](https://www.figma.com/file/U4uRlyJJn92QiNUuyRxSvX/%5BWIP%5D-Grants-Application-%2F-Edit-Flow?node-id=647-5313&t=8xl0WMWxqxeEEcwn-0)

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

### PR DESCRIPTION
**Pull request by KurtMerbeth**
fixes #1528 

image

### CODE REVIEW

**Review by bhargavaparoksham — APPROVED** [review]
@KurtMerbeth code wise lgtm. Some tests are failing please resolve that.

**Review by thelostone-mc — APPROVED** [review]

**Review by michellema1208 — COMMENTED** [review]
@KurtMerbeth - this overall looks good! I love that you also cleaned up our verified badges throughout Builder. I do have a few minor UX nitpicks: 

- [ ] The icon for Payout Wallet Address does not match Figma 
- [ ] Links (website, Twitter, Github username, Github org) should be purple hyperlink 
- [ ] Can remove "@" in Twitter username 
- [ ] Verified badge should be colored in (See Figma) 

Current State: 
Screen Shot 2023-05-08 at 11 10 43 AM


Figma: 
Screen Shot 2023-05-08 at 11 08 19 AM

[Figma link here](https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Builder-S17?type=design&node-id=4775-34225&t=S3lJiNFL57fI9OMg-0)

**Comment by willsputra** [comment]
thanks @KurtMerbeth! we're using the solid shield-check icon from heroicons.

other than what Michelle mentioned, lgtm!

**Comment by thelostone-mc** [comment]
We should do this 
- The icon for Payout Wallet Address does not match Figma
- Verified badge should be colored in (See Figma)

^ Since we added those in the PR -> let's get that fixed
The other two are scope creep.
@michellema1208 Let's only make sure we test what is being added / updated. Anything else we spot during our review which we want to fix should be it's own ticket to avoid scope creep.

**Pull request merged**
