### PR TITLE
feat: round & application page branding updates & integrate report card

### PR DESCRIPTION
**Pull request by cristinalare**
Fixes: #2909

## Description

This PR includes:
- Branding updates for round & application pages
- Report card integration in the round page:
  - Added new /round/:chainId/:roundId/stats page which includes static description, round stats, projects plot and leaderboard
  - Todo after this PR will be merged: 
  a. Add "What people are tweeting" section and allow round operator to update stats page description/preamble & tweets/farcaster list
  b. Add share button & support for dynamic twitter card for the stats page - share to twitter be a link to previous report cards (which have dynamic twitter card) and the previous report cards pages will redirect to explorer

Designs: [Figma](https://www.figma.com/file/5m4EgbkSCMVgc2eSAa18rB/Report-Cards?type=design&node-id=81-3287&mode=design)
## Checklist

This PR:

- [ ] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [ ] Doesn't disable eslint rules.
- [ ] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [ ] If adding/updating a feature, it adds/updates its test script on Notion.

### CODE REVIEW

**Comment by thelostone-mc** [comment]
It looks like there was a messy merge/rebase and there are changes not related to this PR which re already on main
Moving this to draft. Do reopen this once it's resolved

**Comment by gravityblast** [comment]
great job @cristinalare thank you!

I noticed that opening a round goes by default to the stats tab. is that the expected behaviour or do we want to keep the list of applications by default? 

https://explorer-staging-git-fork-cristinalare-feat-55c4a2-grants-stack.vercel.app/#/round/10/0xe9459565709c5e856ffbc3cc8715824945d92de7/

**Comment by cristinalare** [comment]
> great job @cristinalare thank you!
> 
> I noticed that opening a round goes by default to the stats tab. is that the expected behaviour or do we want to keep the list of applications by default?
> 
> https://explorer-staging-git-fork-cristinalare-feat-55c4a2-grants-stack.vercel.app/#/round/10/0xe9459565709c5e856ffbc3cc8715824945d92de7/
 right! the expected behavior is to open the stats tab by default only after the round has ended, i changed this:  https://explorer-haqpmsddi-grants-stack.vercel.app/#/round/10/0xe9459565709c5e856ffbc3cc8715824945d92de7

**Review by melissa-neira — APPROVED** [review]
looks great to me!

**Pull request closed without merging**
