### PR TITLE
fix: fixed avg contribution calc + NaN state display on Manager

### LINKED ISSUE #1541: bug: fix avg contribution calc + "NaN state" display on Manager
**Overview**

Currently, when there are no donations, the Round Stats tab reads "NaN". It should say "N/A" for a more human-readable experience
[Figma](https://www.figma.com/file/V113F2Pp5m2qDM5odXjfFu/Manager-S17?node-id=1508-43896&t=OQbFbxGsR4EZ8x5g-4)

nan

**Steps To Reproduce**
1. Go to https://rmgitcoin.on.fleek.co/
2. Find a round that has received no donations yet 
3. Go to Round Stats tab 
4. Look at "Average Contribution" box which will read "NaN", when it should just say "N/A" 

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

### PR DESCRIPTION
**Pull request by ArslanYM**
##### Description

The Avg. Contribution text will display `N/A` insted of `NaN ` when `round && round.uniqueContributors is not > 0` otherwise the same functionality as before.

##### Refers/Fixes

This PR fixes #1541

##### Testing

Tested this on my local server.

### CODE REVIEW

**Review by vacekj — APPROVED** [review]

**Comment by bard** [comment]
Hey @ArslanYM, there is some diff noise in the patch, i.e. changes in formatting only (line 53 and line 156-157).

It's no big deal in a change this small, but on a bigger one, it would obscure the real changes and put the reviewer at risk of missing something important.

This is probably due to the fact that our project doesn't have a `.prettierrc.json`, so your IDE is using its local settings.

Could you try copying `.prettierrc.json` from https://github.com/gitcoinco/allo-indexer/ into your local `grants-stack` worktree root, save `packages/round-manager/src/features/round/ViewRoundStats.tsx` again, and see if it respects the formatting of the original?

**Comment by ArslanYM** [comment]
> Hey @ArslanYM, there is some diff noise in the patch, i.e. changes in formatting only (line 53 and line 156-157).
> 
> It's no big deal in a change this small, but on a bigger one, it would obscure the real changes and put the reviewer at risk of missing something important.
> 
> This is probably due to the fact that our project doesn't have a `.prettierrc.json`, so your IDE is using its local settings.
> 
> Could you try copying `.prettierrc.json` from https://github.com/gitcoinco/allo-indexer/ into your local `grants-stack` worktree root, save `packages/round-manager/src/features/round/ViewRoundStats.tsx` again, and see if it respects the formatting of the original?

The solution you asked to try doesn't seem to work.

**Comment by bard** [comment]
> > Hey @ArslanYM, there is some diff noise in the patch, i.e. changes in formatting only (line 53 and line 156-157).
> > It's no big deal in a change this small, but on a bigger one, it would obscure the real changes and put the reviewer at risk of missing something important.
> > This is probably due to the fact that our project doesn't have a `.prettierrc.json`, so your IDE is using its local settings.
> > Could you try copying `.prettierrc.json` from https://github.com/gitcoinco/allo-indexer/ into your local `grants-stack` worktree root, save `packages/round-manager/src/features/round/ViewRoundStats.tsx` again, and see if it respects the formatting of the original?
> 
> The solution you asked to try doesn't seem to work.

Could you give it another try, place `.prettierrc.json` in `packages/round-manager` instead of the project root, and see if that gets picked out?

If that also doesn't work, we'll merge the PR as-is.

**Comment by ArslanYM** [comment]
> > > > Hey @ArslanYM, there is some diff noise in the patch, i.e. changes in formatting only (line 53 and line 156-157).
> > > > It's no big deal in a change this small, but on a bigger one, it would obscure the real changes and put the reviewer at risk of missing something important.
> > > > This is probably due to the fact that our project doesn't have a `.prettierrc.json`, so your IDE is using its local settings.
> > > > Could you try copying `.prettierrc.json` from https://github.com/gitcoinco/allo-indexer/ into your local `grants-stack` worktree root, save `packages/round-manager/src/features/round/ViewRoundStats.tsx` again, and see if it respects the formatting of the original?
> > > 
> > > 
> > > The solution you asked to try doesn't seem to work.
> > 
> > 
> > Could you give it another try, place `.prettierrc.json` in `packages/round-manager` instead of the project root, and see if that gets picked out?
> > If that also doesn't work, we'll merge the PR as-is.
> 
> Tried that as well. Doesn't seem to work.

I'll be careful about this next time. Apologies.

**Comment by bard** [comment]
> I'll be careful about this next time. Apologies.

Sorry, I wasn't clear in my explanation, this is none of your fault, rather a bug in our project setup, as it should already include a prettierrc already and ideally autoformat every commit through git hooks (in fact, we have an in-progress PR for this at https://github.com/gitcoinco/grants-stack/pull/2314).

We're currently sorting some build issues and we'll merge this and your other PRs after that. Thanks again for contributing!

**Review by bard — APPROVED** [review]

**Pull request merged**
