### PR TITLE
feat: cart revamp

### PR DESCRIPTION
**Pull request by thelostone-mc**
##### Description

- update the navbar cart icon
- update round page on add to cart with icon 
- update text on the project view page 
- remove shortlist and final ballot and replace with cart
- update tests
- add cart preview icon

Deploy

### CODE REVIEW

**Comment by thelostone-mc** [comment]
test failure is not due to changes in round manager

**Comment by melissa-neira** [comment]
@thelostone-mc looks good to me but the cart nav bar interaction is meant to look like this:
https://www.loom.com/share/ced52f8ff54741dfae6406129cf86416

**Comment by thelostone-mc** [comment]
Gotcha ! we'll capture that in another issue when we actually pick up the milestone 🙌🏼

**Review by melissa-neira — CHANGES_REQUESTED** [review]
The arrow icon in the cart should be a trash icon - just caught this now. See [figma](https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=125-5933&t=a9NiIcAxh1b8zKdh-4) for reference.
screencapture-bafybeif7hkwjnicjy5b4e2p6ccrcvw2nmgracvl2v5ooan2nekbpm45h4u-on-fleek-co-2023-04-04-18_25_11

**Comment by thelostone-mc** [comment]
@melissa-neira fixed

**Pull request merged**
