### PR TITLE
add GTC as payout token for arbitrum

### PR DESCRIPTION
**Pull request by gravityblast**
Fixes: #issue

## Checklist

This PR:

- [ ] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [ ] Doesn't disable eslint rules.
- [ ] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [ ] Doesn't contain commented out code.
- [ ] If adding/updating a feature, it adds/updates its test script on Notion.

### CODE REVIEW

**Review by michellema1208 — CHANGES_REQUESTED** [review]
@gravityblast they actually need GTC on Arbitrum, not Polygon! 

See my ticket: https://github.com/gitcoinco/grants-stack/issues/3067

**Review by michellema1208 — DISMISSED** [review]
@gravityblast - feel free to fix this Monday AM! Running into a decimal error when deploying a round on Arbitrum with GTC as payout token - see below

Screen Shot 2024-03-01 at 12 21 58 PM

Screen Shot 2024-03-01 at 12 22 33 PM

**Review by 0xKurt — APPROVED** [review]

**Comment by 0xKurt** [comment]
> @gravityblast - feel free to fix this Monday AM! Running into a decimal error when deploying a round on Arbitrum with GTC as payout token - see below
> 
> Screen Shot 2024-03-01 at 12 21 58 PM Screen Shot 2024-03-01 at 12 22 33 PM

same for me

**Review by 0xKurt — CHANGES_REQUESTED** [review]
the allo-v1 wrapper uses https://github.com/gitcoinco/grants-stack/blob/main/packages/common/src/payoutTokens.ts as token source which has no GTC token on arbitrum, which causes the error described by @michellema1208

**Comment by vacekj** [comment]
seconding @0xKurt comments

**Review by thelostone-mc — APPROVED** [review]

**Comment by 0xKurt** [comment]
@gravityblast i was able to create a round using GTC, but it doesn't show up on the frontend, which might be another issue.

also i would recommend to remove the payoutTokens from round manager

**Comment by thelostone-mc** [comment]
> also i would recommend to remove the payoutTokens from round manager

lets do this in another PR

**Comment by gravityblast** [comment]
thank you @0xKurt @thelostone-mc , I'm going to create a ticket to merge the 2 mappings

**Pull request merged**
