### PR TITLE
Explorer: [2559] Mobile navbar

### LINKED ISSUE #2559: Explorer: mobile view tab bar
The tab bar isn't displaying correctly in mobile view. See design [here](https://www.figma.com/file/1uxgU2jb0yyN11SUgxARmF/Explorer-S19?type=design&node-id=792-13173&mode=design&t=7cufM7k8h2n8YH8y-4)

### PR DESCRIPTION
**Pull request by carlbarrdahl**
- Fixes #2559

## PR checklist

For every PR, make sure that these statements are true:
- [x] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [x] Doesn't contain type casts and non-null assertions.
- [x] Doesn't add `@ts-ignore`.
- [x] Doesn't disable lints.
- [x] Doesn't use `useState` just for computation - use plain variables instead.
- [x] Splits components into pure components that don't depend on external state or hooks.
- [x] Avoid embedding components within other components
- [x] Doesn't propagate optional values without good reason, doesn't mark property values as optional if that doesn't represent reality.
- [x] Doesn't duplicate existing code.
- [x] Parses out-of-domain data - this includes user input, API respones, on-chain data etc.
- [x] Doesn't contain commented out code.
- [x] Doesn't contain skipped or empty tests.
- [x] If this PR adds/updates any feature, it adds/updates its test script

Subjective - at the discretion of the reviewers
- Does things as simply as possible, but not simpler.
- Doesn't reinvent the wheel or create premature abstractions.

##### Refers/Fixes

fixes #issuenumber

### CODE REVIEW

**Review by bhargavaparoksham — APPROVED** [review]
lgtm.

**Review by melissa-neira — CHANGES_REQUESTED** [review]
hey @carlbarrdahl it looks a little off to me. this is what I'm seeing in my browser:
Screenshot 2023-11-13 at 11 36 31

and [this](https://www.figma.com/file/1uxgU2jb0yyN11SUgxARmF/Explorer-S19?type=design&node-id=792-13173&mode=design&t=9L0g8BsFKWC90e8L-4) is what it's supposed to look like:
Screenshot 2023-11-13 at 11 36 21

**Review by vacekj — APPROVED** [review]
eng wise lgtm

**Comment by carlbarrdahl** [comment]
> hey @carlbarrdahl it looks a little off to me. this is what I'm seeing in my browser: Screenshot 2023-11-13 at 11 36 31
> 
> and [this](https://www.figma.com/file/1uxgU2jb0yyN11SUgxARmF/Explorer-S19?type=design&node-id=792-13173&mode=design&t=9L0g8BsFKWC90e8L-4) is what it's supposed to look like: Screenshot 2023-11-13 at 11 36 21

Thanks! Should be fixed now

**Comment by melissa-neira** [comment]
@carlbarrdahl my apologies if this wasn't clearer before but on the normal desktop view, the tabs should read "Home", "Explore rounds" and "Explore projects". In mobile they should read "Home", "Rounds" and "Projects" - this is so that there's more space in mobile and so that we don't have to use up 2 lines of vertical text. 
I see that in the latest fix, the tabs for the desktop view read like they would for mobile. So all we have to do is to make sure that there are 2 states for the tab bar, one for desktop and one for mobile

**Comment by carlbarrdahl** [comment]
> hey @carlbarrdahl it looks a little off to me. this is what I'm seeing in my browser: Screenshot 2023-11-13 at 11 36 31
> 
> and [this](https://www.figma.com/file/1uxgU2jb0yyN11SUgxARmF/Explorer-S19?type=design&node-id=792-13173&mode=design&t=9L0g8BsFKWC90e8L-4) is what it's supposed to look like: Screenshot 2023-11-13 at 11 36 21

Fixed!

image

**Review by melissa-neira — APPROVED** [review]

**Pull request merged**
