### PR TITLE
QF User Research Report

### PR DESCRIPTION
**Pull request by michellema1208**
##### Description

QF User Research Report: https://www.notion.so/gitcoin/QF-User-Research-Report-4f94dba38f6e41118ddde0c984f33707?pvs=4 

Welcome any thoughts, questions, or feedback!

### CODE REVIEW

**Review by meglister — APPROVED** [review]
I left a few comments in the doc but overall this seems well-researched and a very strong case. Great work!!

**Review by bhargavaparoksham — APPROVED** [review]
lgtm!

**Comment by melissa-neira** [comment]
Looks great to me Michelle!

**Comment by vacekj** [comment]
Looks good - one thing I would add is that the lack of discoverability and general UX of the Explorer homepage is a recurring and strong feedback point from Donors. I've had people tell me in-person in Warsaw, and on Twitter repeatedly that they want to see the "Hidden Gems" and other categories back 😄

**Comment by vacekj** [comment]
@michellema1208 What're the next steps on this?

**Comment by michellema1208** [comment]
@vacekj we're already using this report for upcoming product roadmap validation + docs, so I'll close out this PR! Thanks all for the feedback!

**Pull request closed without merging**
