### PR TITLE
Update Round Metadata Names

### PR DESCRIPTION
**Pull request by boudra**
##### Description

closes https://github.com/gitcoinco/grants-stack/issues/1656

This revamps the quadratic funding config from:

```
matchingFundsAvailable: number
matchingCap: boolean
matchingCapAmount: number
minDonationThreshold: boolean
minDonationThresholdAmount: number
sybilDefense: boolean
```

to

```
matchAmount: number
matchingCapPercentage: number | undefined
minContributionUSD: number | undefined
enablePassport: boolean
```

Hopefully the new field names are simpler and easier to understand.

To get this done I introduced an intermidiate form model that has the following fields (and some function to convert from the form model and the round):

```
matchAmount: number
enableMatchingCap: boolean
matchingCapPercentage: number | undefined
enableMinContribution
minContributionUSD: number | undefined
enablePassport: boolean
```

Ideally we wouldn't need this and we would change the form to not need the boolean variables and just assume an undefined value means it's `false`, and not undefined is `true`, but this refactor would take longer and at this point I just wanted to get the task done.

### CODE REVIEW

**Comment by melissa-neira** [comment]
defer to eng review 🕺

**Review by hmrtn — DISMISSED** [review]
Looks good!

**Comment by boudra** [comment]
whoops sorry for the merge commit 🤔 done automatically by Github

**Review by hmrtn — APPROVED** [review]

**Review by hmrtn — COMMENTED** [review]
Overall this looks good, but there is a build error in the `ViewRoundSettings` component: 
`TS2322: Type 'Control<RoundForm, any>' is not assignable to type 'Control<Round, any>'.`

**Comment by vacekj** [comment]
@boudra what's the status on this?

**Pull request closed without merging**
