### PR TITLE
Explorer: Implement Past and Active round split on Donation History page

### LINKED ISSUE #1898: Explorer: Implement Past and Active round split on Donation History page
**User Story:**
As a DONOR
I want to distinguish my donations to Active Rounds vs. Past Rounds
So that I can easily find my donations 

**Acceptance Criteria**
GIVEN that I've donated to a round that is still running  
WHEN I look at the donation history page
THEN I see my donation to that round in the Active Rounds section 

GIVEN that I've donated to a round that has already ended 
WHEN I look at the donation history page
THEN I see my donation to that round in the Past Rounds section 

**Product & Design Links:**
Figma: https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?type=design&node-id=2122-26445&t=qXYGX5h0cAdtaMQ3-0

**Tech Details:**
This page should live at /donation-history

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

### LINKED ISSUE #1900: Explorer: update breadcrumbs for donation history page
**User Story:**
As a DONOR
I want to be able to navigate to and from my profile 
so that I can easily check my donation history 

**Acceptance Criteria**
GIVEN that I am on my profile page 
WHEN I look at the breadcrumbs 
THEN I see that the navigation is "Explorer Home > Profile" 

**Product & Design Links:**
Figma: https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?type=design&node-id=2122-26445&t=qXYGX5h0cAdtaMQ3-0

**Tech Details:**
This page should live at /donation-history

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

### LINKED ISSUE #1928: Explorer: make the Donation History page mobile-friendly
**User Story:**
As a donor 
I want to see my Donation History page on mobile 
So that I can view my donations on my phone 

**Acceptance Criteria**
GIVEN
WHEN
THEN

**Product & Design Links:**
[Figma](https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?type=design&node-id=2838-56313&t=1cxK4hlBrty99ZfL-4)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

### PR DESCRIPTION
**Pull request by bhargavaparoksham**
##### Description

As a DONOR
I want to distinguish my donations to Active Rounds vs. Past Rounds
So that I can easily find my donations

As a donor
I want to see my Donation History page on mobile
So that I can view my donations on my phone

As a DONOR
I want to be able to navigate to and from my profile
so that I can easily check my donation history

##### Refers/Fixes

fixes #1898 
fixes #1928 
fixes #1900

### CODE REVIEW

**Review by melissa-neira — CHANGES_REQUESTED** [review]
lgtm but just one minor nitpick - the active & past round headers should be bolder than the column headers. In Figma, the active & past round headers are semi-bold and the column headers are medium.

**Review by melissa-neira — COMMENTED** [review]
@bhargavaparoksham breadcrumbs should say "Explorer Home > Profile" currently this is how it looks like on my end:
Screenshot 2023-06-29 at 16 35 27

**Review by melissa-neira — COMMENTED** [review]
as for mobile, everything lgtm except one very minor nitpick - let's get rid of the last dividing line in the rows. This is what it looks like currently for me:
Screenshot 2023-06-29 at 16 37 28
I'm assuming this is the same for desktop as well, but it became more apparent to me while testing the mobile view.

**Review by michellema1208 — APPROVED** [review]

**Review by melissa-neira — DISMISSED** [review]

**Comment by vacekj** [comment]
Still needs some love from the refactoring side, 90% there. Let's pair on this, or I can do it on my own and record it on loom for commentary.

**Review by vacekj — APPROVED** [review]

**Review by melissa-neira — APPROVED** [review]

**Pull request merged**
