### PR TITLE
MRC: Mobile UI fixes on cart page

### LINKED ISSUE #2174: MRC: Mobile UI fixes on cart page
**nav bar**

Screenshot 2023-08-10 at 15 15 47

- the nav bar looks very wonky - it looks like the rainbow kit component is too big here. see [figma](https://www.figma.com/file/4J1WWx7cOd0uUNbI2uA4z0/Explorer-GG18?type=design&node-id=477-11280&mode=design&t=XJnYf7ykk2TZKgzy-4)

**cart**

Screenshot 2023-08-10 at 15 16 49

- the summary box & cart component are too wide for the screen and make the whole page scroll horizontally. I'm testing this on desktop, but with the iPhone 12 pro viewport. 

Screenshot 2023-08-10 at 15 16 57

- the amount & apply all components should span the width of the cart, here it's aligning to the left.

Screenshot 2023-08-10 at 15 18 18

- the input boxes are too wide here (same as on the desktop view) let's make them less wide so that they take up less real estate. reference [figma](https://www.figma.com/file/4J1WWx7cOd0uUNbI2uA4z0/Explorer-GG18?type=design&node-id=222-36874&mode=design&t=XJnYf7ykk2TZKgzy-4) for an appropriate width. since we're not introducing matching estimates, the width of the box can be a bit more than the design, but it's much too wide currently.

### PR DESCRIPTION
**Pull request by bhargavaparoksham**
##### Description

Mobile UI fixes on cart page

##### Refers/Fixes

fixes #2174

### CODE REVIEW

**Review by michellema1208 — COMMENTED** [review]
hey @bhargavaparoksham - Everything Melissa flagged in the original ticket has been fixed - amazing work! 

In reviewing the PR against the Figma, I found 3 other minor UI issues: 

- [ ] The "Amount" label on the cart page has a thicker font weight (see [Figma](https://www.figma.com/file/4J1WWx7cOd0uUNbI2uA4z0/Explorer-GG18?type=design&node-id=222-43407&mode=design&t=wqpJ4kBRJ0Bj9pcM-0) for specs)
- [ ] The "Apply to all" info tooltip is missing on mobile 
- [ ] The text on processing modal on mobile should be left-aligned (See [Figma](https://www.figma.com/file/4J1WWx7cOd0uUNbI2uA4z0/Explorer-GG18?type=design&node-id=222-43407&mode=design&t=wqpJ4kBRJ0Bj9pcM-0))
 
Current view: 
IMG_3059

**Comment by melissa-neira** [comment]
+1 to @michellema1208's comment! thank you for your keen eye 💫

**Review by bard — DISMISSED** [review]

**Review by michellema1208 — DISMISSED** [review]

**Review by vacekj — DISMISSED** [review]

**Review by melissa-neira — CHANGES_REQUESTED** [review]
Everything looks good to me except the thank you page at the end. the image is too far down the page - the user shouldn't have to scroll to see it. Also the twitter and view donation history button don't look like they should - see [figma](https://www.figma.com/file/4J1WWx7cOd0uUNbI2uA4z0/Explorer-GG18?type=design&node-id=222-41609&mode=design&t=IryPeuOtoU4ltlOC-4)
Screenshot 2023-08-25 at 12 55 26

**Review by melissa-neira — APPROVED** [review]
lgtm!

**Review by michellema1208 — APPROVED** [review]

**Pull request merged**
