### PR TITLE
feat: order contributions by date desc in profile + ens support

### LINKED ISSUE #2210: explorer: reverse contributions order in contributors page
**Overview**
Details, details, details

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

### PR DESCRIPTION
**Pull request by vacekj**
Forgive me the unrelated ENS feature, but it took me about 5 minutes, so I thought I would get it in as a nice goodie on top of this PR.

- make view tx an actual link to make it middle-clickable and accesible
- implement ENS support in contributions page
	- ens name works in address bar like `https://explorer.gitcoin.co/#/contributors/vitalik.eth`, in the topbar
	- ENS avatar instead of blockicon, if available
	- if ENS is unavailable or doesn't have a resolved address set, defaults to just displaying address
- fix an unrelated lint error reported by lint:ci

Also, I couldn't find the `_()` wrapper function in `lodash-es`, so I imported `lodash` - tree-shaking should work so nbd, but if anyone can teach me how to import the `_` function from `lodash-es`, I would be grateful.

## PR checklist

For every PR, make sure that these statements are true:
- [x] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [x] Doesn't contain type casts and non-null assertions.
- [x] Doesn't add `@ts-ignore`.
- [x] Doesn't disable lints.
- [x] Doesn't use `useState` just for computation - use plain variables instead.
- [x] Splits components into pure components that don't depend on external state or hooks.
- [x] Avoid embedding components within other components
- [x] Doesn't propagate optional values without good reason, doesn't mark property values as optional if that doesn't represent reality.
- [x] Doesn't duplicate existing code.
- [x] Parses out-of-domain data - this includes user input, API respones, on-chain data etc.
- [x] Doesn't contain commented out code.
- [x] Doesn't contain skipped or empty tests.
- [x] If this PR adds/updates any feature, it adds/updates its test script

Subjective - at the discretion of the reviewers
- Does things as simply as possible, but not simpler.
- Doesn't reinvent the wheel or create premature abstractions.

##### Refers/Fixes

fixes #2210 #1926

### CODE REVIEW

**Review by bhargavaparoksham — COMMENTED** [review]
@vacekj ens is still not resolving for my address. ref: https://explorer-staging-git-2210-explorer-reverse-7f2f14-grants-stack.vercel.app/#/contributors/0xc24e3C2e72f960fa1d54170Fa03492DDa4cE8256

**Comment by vacekj** [comment]
@bhargavaparoksham good catch - fixed. for posterity: the issue was that when a wallet is not connected, all the public actions were trying to load the ens values from goerli for some reason. I set them all to fetch from mainnet instead.

**Comment by bhargavaparoksham** [comment]
@vacekj explorer is build is failing, please check

**Review by melissa-neira — APPROVED** [review]
lgtm! love the ens support!

**Pull request merged**
