### PR TITLE
3318/mrc style updates

### PR DESCRIPTION
**Pull request by codenamejason**
Fixes: #3318 

## Description

To test:

- [x] Add projects from at least 2 different chains and checkout.
- [x] Add projects from only one chain and checkout.

## Checklist

This PR:

- [x] Does it add new payout or donation token? In this case, have they been added to the indexer to avoid it to crash?
- [x] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [x] Doesn't disable eslint rules.
- [x] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [x] Doesn't contain commented out code.
- [x] If adding/updating a feature, it adds/updates its test script on Notion.

### CODE REVIEW

**Review by thelostone-mc — APPROVED** [review]

**Review by 0xKurt — APPROVED** [review]

**Review by michellema1208 — COMMENTED** [review]
I'm helping test design changes on behalf of Melissa while she's OOO this week! 

@codenamejason @0xKurt - confirming that the flow works for both MRC and single-round checkout -- great work as usual, and the UI looks sooo much better (h/t @melissa-neira !!) 

My only question: is the "+X gas fee" meant to be hardcoded here, or is it supposed to actually display the estimated gas fee per chain? My guess is that the "+X gas fee" in Melissa's designs was meant to be a placeholder for the actual amount, not something we actually show to end users. I'm not sure if @codenamejason / @0xKurt if you synced with Melissa on this and have more context? 

Screen Shot 2024-04-22 at 3 22 08 PM

**Comment by codenamejason** [comment]
we don't calculate the gas fee, the users wallet does. Keep me honest @0xKurt

**Comment by thelostone-mc** [comment]
I don't think we need to add X gas fees. It's pretty evident that you'd have to pay gas fees

**Review by michellema1208 — APPROVED** [review]
Approving this on the premise that "+ X gas fee" gets removed first per above comment!

**Pull request merged**
