### PR TITLE
Add download applications CSV button

### PR DESCRIPTION
**Pull request by boudra**
##### Description

Depends on this being merged first: https://github.com/gitcoinco/allo-indexer/pull/27

Screenshot 2023-04-13 at 15 50 46

### CODE REVIEW

**Review by melissa-neira — CHANGES_REQUESTED** [review]
A small change:
- The spacing between the CSV button and the select button is a bit off. Those elements are meant to be aligned with each other. [Figma](https://www.figma.com/file/V113F2Pp5m2qDM5odXjfFu/Manager-S17?node-id=234-21076&t=DakhbpxP3C2PsJIy-4)

I'm also getting an error when I click on the CSV button but I assume it's because the dependent PR hasn't been merged yet.

**Comment by boudra** [comment]
@melissa-neira my bad, I didn't test the button with applications so there was no select button 🙈 it should be fixed now

Also the CSV download should work now!

**Comment by melissa-neira** [comment]
@boudra The button is in the right place now but the CSV file is empty when I download it :/ is anyone else experiencing this?

**Comment by boudra** [comment]
@melissa-neira what round are you looking at, can I have an address 🙏

**Comment by melissa-neira** [comment]
@boudra #/round/0x6ef12147abdb55c12fe3dbb0865194ddc890fd12

**Comment by nfrgosselin** [comment]
yeah @boudra I'm having the same issue as Melissa on this round: /#/round/0x12bb5bbbfe596dbc489d209299b8302c3300fa40

image

image

**Comment by melissa-neira** [comment]
@boudra the CSV is populated now but the email address field seems to be a little wonky. Everything else is working!
Screenshot 2023-04-14 at 19 34 02

**Comment by boudra** [comment]
> @boudra the CSV is populated now but the email address field seems to be a little wonky. Everything else is working!
> Screenshot 2023-04-14 at 19 34 02
> 

yeah the email address is stored encrypted and we cannot decrypt it here

 @gravityblast can you confirm, is there any way for us to show the email address in the CSV? my guess is we would have to add a transform step in the front end?

**Review by nfrgosselin — APPROVED** [review]

**Pull request merged**
