### PR TITLE
fix: fix build

### LINKED ISSUE #2216: grant-explorer doesn't build
```
/home/bard/projects/gitcoin/grants-stack/node_modules/.pnpm/react-scripts@5.0.1_@babel+plugin-syntax-flow@7.18.6_@babel+plugin-transform-react-jsx@7.20.7_xf3jho5iktresnxqrlkjr2ggmi/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^

TypeError: The 'compilation' argument must be an instance of Compilation
    at NormalModule.getCompilationHooks (/home/bard/projects/gitcoin/grants-stack/node_modules/.pnpm/webpack@5.75.0_esbuild@0.16.17/node_modules/webpack/lib/NormalModule.js:227:10)
    at /home/bard/projects/gitcoin/grants-stack/node_modules/.pnpm/webpack-manifest-plugin@4.1.1_webpack@5.75.0/node_modules/webpack-manifest-plugin/dist/index.js:58:42
    at _next46 (eval at create (/home/bard/projects/gitcoin/grants-stack/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:50:1)
[...]
<anonymous>:152:1)
    at Hook.CALL_DELEGATE [as _call] (/home/bard/projects/gitcoin/grants-stack/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/bard/projects/gitcoin/grants-stack/node_modules/.pnpm/webpack@5.75.0/node_modules/webpack/lib/Compiler.js:1122:26)
    at /home/bard/projects/gitcoin/grants-stack/node_modules/.pnpm/webpack@5.75.0/node_modules/webpack/lib/Compiler.js:1166:29
    at Hook.eval [as callAsync] (eval at create (/home/bard/projects/gitcoin/grants-stack/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
```

(only opening for tracking — fix incoming)

### LINKED ISSUE #2294: fix vercel build
Likely will be fixed by #2219 once done.

### PR DESCRIPTION
**Pull request by bard**
##### Refers/Fixes

closes #2216
closes #2294 

##### Testing

Note: PR checks are failing on lockfile because I didn't push my v8 lockfile. If you want to stick with pnpm 7, before approving review please check out this branch, run `pnpm i`, and commit the resulting lockfile. Otherwise I can push the v8 lockfile and we can catch this as opportunity to move to a maintained version of pnpm.

### CODE REVIEW

**Comment by melissa-neira** [comment]
defer review to the eng team

**Comment by gravityblast** [comment]
I agree to move to v8. if we do it, do we need any change in the github action files?

**Review by bhargavaparoksham — CHANGES_REQUESTED** [review]
builds are failing, please fix them.

**Comment by bard** [comment]
> builds are failing, needs to be resolved.

@bhargavaparoksham please see PR description. This needs to be fixed by you, @vacekj, or someone else who is using pnpm 7.

**Comment by vacekj** [comment]
@bard let's use this as an opp. to move to pnpm v8

**Comment by bard** [comment]
@vacekj I committed the lockfile from v8. However, after rebasing on main`, I got build errors:

1. the `RoundsGroup` type was misspelled as `RoundGroups` (fixed)
2. `@reduxjs/toolkit` was now in package.json (fixed)
3. the following (not fixed):

```
> pnpm turbo build

╭────────────────────────────────────────────────────────────────────────╮
│                                                                        │
│                  Update available v1.10.9 ≫ v1.10.12                   │
│    Changelog: https://github.com/vercel/turbo/releases/tag/v1.10.12    │
│               Run "npx @turbo/codemod update" to update                │
│                                                                        │
│      Follow @turborepo for updates: https://twitter.com/turborepo      │
╰────────────────────────────────────────────────────────────────────────╯
• Packages in scope: builder, common, eslint-config-gitcoin, grant-explorer, round-manager
• Running build in 5 packages
• Remote caching disabled
grant-explorer:build: cache miss, executing 693884139f14fb51
grant-explorer:build: 
grant-explorer:build: > grant-explorer@0.1.0 build /home/bard/projects/gitcoin/grants-stack/packages/grant-explorer
grant-explorer:build: > env REACT_APP_GIT_SHA=$(git rev-parse --short HEAD) craco build
grant-explorer:build: 
grant-explorer:build: Creating an optimized production build...
grant-explorer:build: [BABEL] Note: The code generator has deoptimised the styling of /home/bard/projects/gitcoin/grants-stack/packages/grant-explorer/src/assets/404.svg as it exceeds the max of 500KB.
grant-explorer:build: [BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.
grant-explorer:build: [BABEL] Note: The code generator has deoptimised the styling of /home/bard/projects/gitcoin/grants-stack/packages/grant-explorer/src/assets/landing-banner.svg as it exceeds the max of 500KB.
grant-explorer:build: [BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.
grant-explorer:build: Failed to compile.
grant-explorer:build: 
grant-explorer:build: TS2590: Expression produces a union type that is too complex to represent.
grant-explorer:build:     35 |           {new Array(3).fill(undefined).map((_, index) => {
grant-explorer:build:     36 |             return (
grant-explorer:build:   > 37 |               <Skeleton key={index} my={3} rounded={"md"} w={"full"} h={"64"} />
grant-explorer:build:        |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grant-explorer:build:     38 |             );
grant-explorer:build:     39 |           })}
grant-explorer:build:     40 |         </div>
grant-explorer:build: 
grant-explorer:build: 
grant-explorer:build:  ELIFECYCLE  Command failed with exit code 1.
grant-explorer:build: ERROR: command finished with error: command (/home/bard/projects/gitcoin/grants-stack/packages/grant-explorer) pnpm run build exited (1)
grant-explorer#build: command (/home/bard/projects/gitcoin/grants-stack/packages/grant-explorer) pnpm run build exited (1)
```

**Comment by vacekj** [comment]
That's a tsc-specific error. You can ts-expect-error it. @bard

**Comment by vacekj** [comment]
> > That's a tsc-specific error. You can ts-expect-error it. @bard
> 
> I know, the question is, should we?
I'm already funding https://github.com/dudykr/stc and https://github.com/kaleidawave/ezno to replace tsc.
On a serious note, I would say yes in this case, unless we manage to "fix" the error in some sane way, but I would write this off as a shortcoming of tsc and explain this in the expect-error comment.

**Comment by bard** [comment]
Further discussion: https://discord.com/channels/562828676480237578/1146613587780046900

**Comment by vacekj** [comment]
> @bhargavaparoksham @vacekj for 150% completeness you might want to set up builds on vercel for builder and round-manager too

on it

**Review by vacekj — APPROVED** [review]

**Review by bhargavaparoksham — APPROVED** [review]

**Review by vacekj — APPROVED** [review]

**Pull request merged**
