### PR TITLE
1784 - adding public/private to edit flow

### LINKED ISSUE #1784: Manager: add ability to edit public/private selection for round
**User Story:**
As a
I want to
So that

**Acceptance Criteria**
GIVEN
WHEN
THEN

**Product & Design Links:**
* Make this editable in the Round Details page 

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

### PR DESCRIPTION
**Pull request by codenamejason**
Closes #1784 

Adds the ability to edit your `public` or `private` status for exposure on grant explorer.

Screenshot 2023-05-22 at 12 42 39 PM

### CODE REVIEW

**Review by michellema1208 — CHANGES_REQUESTED** [review]
hey @codenamejason - I just tested this, and looks like I'm running into the following issue:

- [ ] when I change my public/private selection (i.e. changing previously Public round to private, or vice versa), it's not letting me update the round 

I also found another bug while testing, but it looks like it's also happening on staging, so I'm tracking it separately here: https://github.com/gitcoinco/grants-stack/issues/1856

**Comment by michellema1208** [comment]
@codenamejason just tested this again - am still running into the same issue as above! Once I change my public/private selection, I can't update the round

**Comment by willsputra** [comment]
@codenamejason @KurtMerbeth just tested this - it worked for me! one small request: could we add more spacing between the options, like how we have it on the round creation flow? otherwise lgtm! :)

round edit:
image

round creation:
image

**Comment by michellema1208** [comment]
@codenamejason @KurtMerbeth - now changes are being saved! Only hiccup: I can't test if the newly public round is showing up on Explorer, as the explorer build is queued. That should be working now with the Fleek plan updated with the credit card?

**Comment by michellema1208** [comment]
@codenamejason @KurtMerbeth great thanks! It's working now from a functionality POV. Once Will's UX callout is addressed (https://github.com/gitcoinco/grants-stack/pull/1852#issuecomment-1563221712), I'll go ahead and approve this PR.

**Comment by KurtMerbeth** [comment]
> @codenamejason @KurtMerbeth just tested this - it worked for me! one small request: could we add more spacing between the options, like how we have it on the round creation flow? otherwise lgtm! :)
> 
> round edit: image
> 
> round creation: image

done
image

**Review by michellema1208 — APPROVED** [review]

**Review by michellema1208 — APPROVED** [review]

**Review by willsputra — APPROVED** [review]

**Review by hmrtn — APPROVED** [review]

**Review by hmrtn — APPROVED** [review]

**Comment by hmrtn** [comment]
Approved and works as expected - but again, these components should really be part of the common base components - it introduces redudancy with the same functionality, and will only get more difficult to refactor in the future.

**Comment by vacekj** [comment]
@hmrtn agreed - let's not merge before the components are properly extracted into common. No more tech debt.

**Review by michellema1208 — APPROVED** [review]
LGTM!

**Pull request merged**
