### PR TITLE
add arbitrum round link to gg18 subnav

### LINKED ISSUE #2242: Add Arbitrum to Featured Round Dropdown
**Overview**
Name: Arbitrum Domain Round
Link: https://explorer.gitcoin.co/#/round/1/0x69e423181f1d3e6bebf8ab88030c36da73785f26

This was a late add to GG18, let's update the menu to reflect it

Image

### PR DESCRIPTION
**Pull request by gravityblast**
closes #2242

### CODE REVIEW

**Review by michellema1208 — CHANGES_REQUESTED** [review]
hey @gravityblast - I just tested this, flagging two issues: 

- [ ] With the new round, the dropdown is too close to the end of the page - can we make the dropdown a bit smaller? 
Screen Shot 2023-08-21 at 11 33 33 AM 

- [ ] When I click on the Arbitrum link through this PR, I get a 404 page (Link: https://bafybeicc7j5s3geczjgfavhtcqaeglejujqgpoz5sqazzimruv6kfzeyx4.on.fleek.co/#/round/1/0x69e423181f1d3e6bebf8ab88030c36da73785f26) 

However, if I just go to the page directly on Explorer, it works: https://explorer.gitcoin.co/#/round/1/0x69e423181f1d3e6bebf8ab88030c36da73785f26

**Comment by gravityblast** [comment]
@michellema1208 we can't, cause it depends only on the size of the screen, so we can't have something that's always far from the end of the screen

**Comment by gravityblast** [comment]
@michellema1208 I updated an env variable on fleek and it's building again, when it's ready it should be fixed using the prod subgraph

**Comment by gravityblast** [comment]
@michellema1208 is it ok now?

**Review by bhargavaparoksham — APPROVED** [review]

**Review by vacekj — APPROVED** [review]

**Review by michellema1208 — APPROVED** [review]

**Pull request merged**
