### PR TITLE
fix: don't hide "apply" button before application end time

### PR DESCRIPTION
**Pull request by bard**
Fixes: #2751 

## Description

- enable/disable badges based on absolute time instead of (integer) days left, since "0 days" really means "between 23h59m59s and 0s"
- added `getRoundPhase` that can be extended and used to answer the question "in what phase is this round?" (`accepting-applications`, `active`, `ended`, ...)
- added tests for `getDaysLeft`

## Testing

1. in the home page in PR environment, click on "Explore Rounds"
2. verify that all rounds which are accepting applications (especially those in the last day) display the "Apply!" button

## Checklist

This PR:

- [x] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [x] Doesn't disable eslint rules.
- [x] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [x] Doesn't contain commented out code.
- [x] If adding/updating a feature, it adds/updates its test script on Notion.

### CODE REVIEW

**Review by vacekj — APPROVED** [review]
beautiful, lgtm

**Comment by melissa-neira** [comment]
Screenshot 2023-12-19 at 17 16 59
I see some projects that are taking applications do not have the "apply" badge here. as a rule, projects that are taking applications should always have that apply badge visible

**Comment by meglister** [comment]
@bard having trouble testing this one -- can you suggest steps?

**Comment by bard** [comment]
@melissa-neira Yes, that's exactly the bug that the PR is meant to solve, but I mistakenly assumed that application time would always end before round time started, and introduced a different bug. Great catch, I'll push a fix.

@meglister Will add testing steps after fixing the above.

**Review by meglister — APPROVED** [review]
thanks! I was looking at the apply button on individual round pages and very confused. lgtm :)

**Review by boudra — APPROVED** [review]

**Pull request merged**
