### PR TITLE
feat: make project details page more responsive

### LINKED ISSUE #1639: Explorer: Project details text width too narrow
**Overview**
The project description width is too narrow on the project details page, leaving a lot of white space that doesn't look great (especially on wider screens).

This is what it looks like:
1440px width
Screenshot 2023-04-27 at 13 16 49

much wider width
Screenshot 2023-04-27 at 13 17 03

**Details**
The text should always be the width of the gray dividing lines above it (there should be a breakpoint to this though so the width doesn't get out of hand.) The more responsive we can make this page, the better. See [Figma](https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=526-15098&t=hoZer7opXuWcAiiF-4) for reference.

### PR DESCRIPTION
**Pull request by vacekj**
fixes #1639

### CODE REVIEW

**Review by bhargavaparoksham — DISMISSED** [review]

**Review by michellema1208 — CHANGES_REQUESTED** [review]
@vacekj just tested this! I'm seeing the same issue that @melissa-neira called out earlier - looks like the margins on the project page don't match the rest of the site, and should look more like what Melissa has in [Figma](https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?type=design&node-id=526-14125&t=g4wDBEF64Yp3MQR1-0). 

What I'm seeing: 
Screen Shot 2023-05-30 at 4 32 34 PM

**Review by melissa-neira — CHANGES_REQUESTED** [review]
Text content is looking good, but the banner is not. Can you please make sure it's always the same width as the text content? 💗
Screenshot 2023-06-01 at 15 49 12

**Review by hmrtn — APPROVED** [review]

**Comment by hmrtn** [comment]
lgtm

**Comment by michellema1208** [comment]
@vacekj - it looks like the builds are queued so I'm not able to test. Can you ping me once that's ready and I'll help test here?

**Comment by vacekj** [comment]
@michellema1208 https://bafybeig4gw5eetoibx3jo3ldxe7u347tgyotbm7xzffyegqmbxfl6go6fa.on.fleek.co

**Review by michellema1208 — APPROVED** [review]
LGTM!

**Pull request merged**
