### PR TITLE
Add usdc as a payout token on polygon

### LINKED ISSUE #2508: [Polygon] Manager: add USDC support as a matching pool payout token on Polygon
**User Story:**
As a Round Manager 
I want to be able to set USDC as my matching pool payout token 
So that I can payout my grantees in USDC 

**Acceptance Criteria**
GIVEN that I am setting up a round on Polygon 
WHEN I select payout token 
THEN I see that USDC is a payout token option 

GIVEN that I've created a Polygon round with USDC as my payout token 
WHEN I go to the Fund Contract tab 
THEN I see that my payout token is USDC
AND I can fund my contract in USDC

GIVEN that I've created a Polygon round with USDC as my payout token 
WHEN I go to the Round Stats tab 
THEN I see Matching Funds Available is denoted in USDC

**Product & Design Links:**

**Tech Details:**
* 

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

### LINKED ISSUE #2510: [Polygon] Explorer: Add support for USDC on Polygon as a donation token
**User Story:**
As a donor 
I want to donate in USDC to projects in rounds deployed on Polygon 
So that I have alternatives to donating in the native token (MATIC) 

**Acceptance Criteria**
GIVEN that I have added a project from a round deployed on Polygon 
WHEN I am checking out 
THEN I can select USDC as my donation token 
AND set my donation amount in USDC

**Product & Design Links:**

**Tech Details:**
* USDC Contract on Polygon: https://polygonscan.com/token/0x2791bca1f2de4661ed88a30c99a7a9449aa84174?a=0x71c7656ec7ab88b098defb751b7401b5f6d8976f

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

### PR DESCRIPTION
**Pull request by bhargavaparoksham**
## PR checklist

For every PR, make sure that these statements are true:
- [x] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [x] Doesn't contain type casts and non-null assertions.
- [x] Doesn't add `@ts-ignore`.
- [x] Doesn't disable lints.
- [x] Doesn't use `useState` just for computation - use plain variables instead.
- [x] Splits components into pure components that don't depend on external state or hooks.
- [x] Avoid embedding components within other components
- [x] Doesn't propagate optional values without good reason, doesn't mark property values as optional if that doesn't represent reality.
- [x] Doesn't duplicate existing code.
- [x] Parses out-of-domain data - this includes user input, API respones, on-chain data etc.
- [x] Doesn't contain commented out code.
- [x] Doesn't contain skipped or empty tests.
- [x] If this PR adds/updates any feature, it adds/updates its test script

Subjective - at the discretion of the reviewers
- Does things as simply as possible, but not simpler.
- Doesn't reinvent the wheel or create premature abstractions.

##### Description

Add usdc as a payout token on polygon

##### Refers/Fixes

fixes #2508 
fixes #2510

### CODE REVIEW

**Review by carlbarrdahl — APPROVED** [review]
Looks good to me

**Comment by gravityblast** [comment]
@bhargavaparoksham @michellema1208 is the token added here the right one? (https://polygonscan.com/address/0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359)

the issue linked points to USDC.e https://polygonscan.com/address/0x2791bca1f2de4661ed88a30c99a7a9449aa84174

**Review by vacekj — APPROVED** [review]

**Comment by vacekj** [comment]
@gravityblast @bhargavaparoksham I remember us having this convo before and deciding for the native USDC, but don't remember if it was polygon or some other chain. @michellema1208 @meglister to confirm please.

**Review by michellema1208 — APPROVED** [review]
LGTM - great work as usual, Bhargav!

**Pull request merged**
