### PR TITLE
fix: preview bar on builder

### LINKED ISSUE #1895: Builder: remove the "this is a preview..." copy on the application page
**Overview**
**Problem**: The "This is a preview..." copy appears at the top of the Application Questions page if the user clicks Preview and then clicks Back to return to the Application Questions page, when it should only appear on the Application Preview page. 

**Steps To Reproduce**
1. Go to an application page (i.e. try: https://staging.grantshub.gitcoin.co/#/chains/5/rounds/0x6a14a04f11720264393ef3bfb679484494ef9f8a) 
2. Fill out application information 
3. Click on Preview to go to the Application Preview page 
4. Click on Back to return back to the Application Questions page 
5. When you look at the page, the "This is a preview..." copy stays at the top of the page, even though it is no longer the Application Preview page

### PR DESCRIPTION
**Pull request by hmrtn**
fixes #1895

### CODE REVIEW

**Review by michellema1208 — CHANGES_REQUESTED** [review]
@hmrtn - the bug of the copy repeating on the wrong pages is now resolved - great work! One minor piece of UX feedback as well: the copy should be left-aligned, not centered. See Figma below! (Note: the copy in the Figma is currently outdated - please use the copy that we currently have in app) 

[Figma](https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Builder-S17?type=design&node-id=4775-34225&t=9k4IYIsryb0d4YEe-0): 
Screen Shot 2023-06-05 at 9 49 52 AM

**Comment by melissa-neira** [comment]
+1 to @michellema1208's comment

**Review by michellema1208 — APPROVED** [review]

**Review by melissa-neira — CHANGES_REQUESTED** [review]
The preview bar should be center-aligned with the exit button. Other than that, lgtm!
this is what it looks like on my computer:
screencapture-bafybeif6mavr3anjuxbg3fdj46zmpjbwh3ytwyv4frfyimaryvyhiqdcdq-on-fleek-co-2023-06-07-13_01_39

one other thing (this doesn't fall into the scope of this ticket prob) but when I was testing, I noticed that the pre-application screen said that the round that I just created had ended. This screen should've said that applications hadn't opened yet. @michellema1208, should we spin up a new ticket to track this? 
Screenshot 2023-06-07 at 12 56 56

**Comment by hmrtn** [comment]
The reason the component sits below the exit button is because of the form component structure. We can fix this hackly, or correctly, - but I think it is more work than simply accepting the slight difference. Thoughts @melissa-neira @michellema1208 ?

**Review by melissa-neira — APPROVED** [review]
@hmrtn good point! no worries then, this lgtm 😎

**Review by bhargavaparoksham — APPROVED** [review]

**Pull request merged**
