### PR TITLE
fix: apply button color

### LINKED ISSUE #1531: Explorer: change Apply button to purple instead of white
[Figma](https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?node-id=483-10998&t=KkIwGOPE3IBzNwBr-4)

**User Story:**
As a
I want to
So that

**Acceptance Criteria**
GIVEN
WHEN
THEN

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

### PR DESCRIPTION
**Pull request by vacekj**
fixes #1531 

round to check: /#/round/5/0x1161fae3274be56f6d9286cb363fc2b43d0f48cb

### CODE REVIEW

**Comment by melissa-neira** [comment]
@vacekj I don't think we have that hover state applied anywhere else across our products - can we just leave it as a static purple button for now? Branding changes/updates are going to be coming soon but I don't want to stray too far from design consistency before then

**Comment by vacekj** [comment]
@melissa-neira fixed

**Comment by melissa-neira** [comment]
@vacekj One other tiny change - I see a light gray border/stroke around the button currently. Can you get rid of that please?

**Comment by vacekj** [comment]
@melissa-neira fixed

**Review by boudra — APPROVED** [review]

**Review by melissa-neira — APPROVED** [review]
lgtm!

**Pull request merged**
